### PR TITLE
Fix selector error

### PR DESCRIPTION
**Pull request by cat-bro**
selectItems takes an array as argument

### CODE REVIEW

**Comment by scaredcat** [comment]
why does this need to be an array? I feel that you can simply use the id that from the parameter passed to the callback and add it to an array if you need it in that format.

**Comment by cat-bro** [comment]
It's currently broken - when you click on a checkbox you get a js error (.. .forEach is not a function)

There are two ways of fixing it.  One way is to make sure that the callback always has an array as argument.  The other way would be to allow the callback to take either an array or a single item, and change the docstrings to reflect this.

Both ways are valid imo.

**Comment by cat-bro** [comment]
It makes sense, since selectItems also takes 'all' or null as input, that it should be able to handle a single item.  Will make a PR in for the parent selectItems function.

There are a couple of lines remaining here - just altering prop descriptions around selectItems

**Comment by scaredcat** [comment]
I see what you mean. I agree, both are valid approaches

**Pull request merged**
